### ISSUE TITLE
Impossible to log in to admin pannel

### ISSUE THREAD

**Issue by Zdav** [Nuked-Klan/CMS_Nuked-Klan#100]
When i try to login to admin panel 

I have a white page.

**Comment by akred** [comment]
Hello Zdav,
Did you experiment any issue on the last current code : https://github.com/Nuked-Klan/CMS_Nuked-Klan/commit/e3e38acfb3817c9d18ff74cc5744392d808c3869

Thanks

**Comment by Zdav** [comment]
no i tried it about 3 weeks ago, i will set up a test site where you can log on to verify this bug.
Before i tested this one on a local server (using Wamp) and on web site online. 
I had the bug in both cases.

**Comment by Zdav** [comment]
hmmm all the website(also in front end) is a withe page now (INSTALL was ok) Oo:
http://lab.fragz.fr/index.php 

White page on FF
Erreur 500 on Google Chrome
Same on IE 11

host name is proxgroup.fr (redheberg old name)

**Comment by Zdav** [comment]
Admin is reachable now
