### ISSUE TITLE
Website official down ?

### ISSUE THREAD

**Issue by ZerooCool** [Nuked-Klan/CMS_Nuked-Klan#129]
Website official down ?

**Comment by Stive1987** [comment]
Yes org is down
Transfert https://nuked-klan.fr

**Comment by ZerooCool** [comment]
Ok, thank you.
I have change the link, to my website.
https://www.visionduweb.eu/wiki/index.php?title=CMS

**Comment by ZerooCool** [comment]
Je relisais le code source proposé sur le dépôt, et, le readme.
Le cms tourne vraiment encore sur PHP 5.4 ?
On est tout de même passé à PHP 7.2, PHP 7.3 étant a l'essai.

**Comment by Stive1987** [comment]
Il est compatible avec le 7.2 sur la dernière branche du gît, j'ai pas testé personnellement, faudrait que je test.
pour votre site je ferais le changement dans l'après midi

**Comment by ZerooCool** [comment]
Merci pour l'information, pour la version de PHP.
J'ai partagé mon site car je partage le lien du projet.
Je ne crois pas avoir créé un compte, ni être affiché chez vous pour le moment.
Normalement, tu n'as aucun changement à faire à ce niveau, sauf, si tu souhaites m'afficher.
A bientôt.

**Comment by Stive1987** [comment]
Re, j'ai bien enregistré votre site web, par contre, je ne savais pas quoi trop mettre en description.

[https://nuked-klan.fr/index.php?file=Links&op=description&link_id=106](url)

**Comment by ZerooCool** [comment]
Re *
Quoi mettre en description, c'est une question que je me pose encore moi même ...
Pour ma part, le terme HackerSpace me plait, car, il me convient du fait des nombreux échanges virtuels initiés sur le réseau, et, également du fait que je suis Space, comme Hacker.

En ce moment, je tente d'avancer sur la gestion de serveur, et, également, sur Redmine.
Mon wiki présente pas mal de recherches personnelles : https://www.visionduweb.eu/wiki/index.php?title=Sp%C3%A9cial:Toutes_les_pages

Dans ce dernier projet que je tente d'aboutir au niveau technique, j'aimerais permettre à la "masse" de faire des propositions, pour l'écologie, et, de les réaliser en commun. Une forme de lobby citoyen écolo.
http://unis-pour-le-climat.com/redmine/projects/unis-pour-le-climat

Si le projet vous semble intéressant, nécessaire, n'hésitez pas à me contacter
https://www.visionduweb.eu/contact
