### ISSUE TITLE
Bug in code tag CKeditor (email)

### ISSUE THREAD

**Issue by akred** [Nuked-Klan/CMS_Nuked-Klan#13]
When a user post a message using the tag code, the displayed result is wrong.
To reproduce the problem, you have to write en email adress.
The displayed result will contains javascript after email.

**Comment by Zdav** [comment]
Hello Akred, 

Can you give more explanation about this bug.
I tryed to reproduce it but  didn't find it

What's module? ckeditor function?(code or source etc.

Thank you

**Comment by Zdav** [comment]
Bug trouvé, je n'arrivai pas a reproduire sur un thème qui inclus beaucoup de JS

**Comment by akred** [comment]
Fix with 1.8 version
