### ISSUE TITLE
No CSS inclusion in Vote Module

### ISSUE THREAD

**Issue by Zdav** [Nuked-Klan/CMS_Nuked-Klan#26]
L'inclusion CSS ne se fait pas sur le module Vote.

Hypothèse de bug : Le module vote n'est jamais passé en URL et est considéré comme une fonction appelé par un module.

**Comment by akred** [comment]
"Vote" and "Comment" are not $REQUEST['file'](not a real modules like forum or others).
So the function printMedias() of  Includes/nkMediaIncludes.php is never use for those modules.

If we need to include CSS for those modules, we can use "nkTemplate_addCSSFile" at the top of the index.php for "Comment" and "Vote"

The goal is to get rid of printMedias() function and use nkTemplate system
