### ISSUE TITLE
Module User > Membres non validés

### ISSUE THREAD

**Issue by antares-dk** [Nuked-Klan/CMS_Nuked-Klan#27]
Bonjour, lorsque j'ai des membres non validés (dans l'administration) et que je clique sur éditer.
Les informations du membres disparaissent, on se retrouve avec un formulaire vide et si on fait retour, ou page préc avec la souris (ou le bouton du navigateur) la liste des membres non validés se vide irrémédiablement.

J'avais déjà remarqué mais je pensais avoir fait des mauvaises manipulation, mais à priori cela se répète systématiquement.
Bonne continuation

**Comment by Zdav** [comment]
Bonjour Antarès,

Nous avons déjà répertorié ce bug.
Le module User ayant déjà été refait sur la 1.8 , il a surement été corrigé sur la nouvelle version.

Je ferme donc ce ticket.
Merci pour ta participation
