### ISSUE TITLE
Forum bug

### ISSUE THREAD

**Issue by xEvoZ** [Nuked-Klan/CMS_Nuked-Klan#32]
Bonjour, j'ai quelques petits soucis avec mon forum. Cela date d'il y a 1 an et demi déjà j'avais installer NukedKlan pour ma team. Mais lorsque nous postions des messages sur le forum il nous affichais souvent Code HTML Mal formaté. Et en ce moment je suis embêter par des poste que je doit refaire completement car si je l’édit et que j'accepte les changements les images ne s'affiche plus ou le texte prends des caractère spéciaux Merci beaucoup. 

Mon site: www.AoLGaming.net

**Comment by Zdav** [comment]
Certains codes sont interdits via l'éditeur HTML. Il se peux que vous ayez rencontré ce souci suite à l'insertion d'un code html qui ne passe pas le filtre de sécurité de l'éditeur HTML.
