### ISSUE TITLE
javascript error with index.php

### ISSUE THREAD

**Issue by Zdav** [Nuked-Klan/CMS_Nuked-Klan#4]
J'ai constaté un conflit javascript avec la version et plusieurs thèmes utilisant cette technologie.

RAS lorsque l'on replace le fichier index de la 1.79 finale, le js fonctionne, Ckedtor fonctionne aussi , en revanche une erreur js est constaté avec le syntaxhiglighter.

**Comment by Zdav** [comment]
Ligne 137 du fichier index.php on à déja un : 

<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>

RAS lorsque l'on commente cette ligne.

**Comment by Zdav** [comment]
pff comment censuré^^ : *jquery-latest.min.js

**Comment by samoth93** [comment]
checker si jquery n'est pas déjà chargé par le thème avant de l'inclure dans l'index de NK

**Comment by Zdav** [comment]
Bug résolu
