### ISSUE TITLE
Caractere speciaux

### ISSUE THREAD

**Issue by luniun** [Nuked-Klan/CMS_Nuked-Klan#80]
Bonjour, 

Lors de l'installation de NK 1.7.12 ou 1.8.  Les caractere "é" apparaisse avec un "?" . Une solution ?

![nuked](https://cloud.githubusercontent.com/assets/7089175/9831546/5590cf34-595d-11e5-9a75-403d9a6a850a.JPG)

Merci davance

**Comment by cyrillePrigent** [comment]
Bonjour,
Il y a un patch qui permet de corriger le problème d'encodage pour la dernière version.

https://www.nuked-klan.org/index.php?file=Forum&page=viewtopic&forum_id=6&thread_id=4074&p=4#48491

Il est prévu qu'il soit intégré à la prochaine version.

https://github.com/Nuked-Klan/CMS_Nuked-Klan/issues/75

**Comment by luniun** [comment]
Merci pour ton aide. Par contre le lien du patch pour la 1.8 est mort.....

Et pour la 1.7.12 sa ne fonctionne pas ...

je suis sous debian 7 64. avec php 

PHP 5.6.13-1~dotdeb+7.1 (cli) (built: Sep  4 2015 17:30:11)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by cyrillePrigent** [comment]
Désolé, mon hébergeur gratuit m'a totalement vider mon ftp...
Vu que tu est sous php 5.6, tu peut très facilement corrigé les accents, il te suffit de rajouter :

`ini_set('default_charset', 'ISO8859-1');`

au début des fichiers : 
- ban.php
- index.php
- opensearch.php
- tout les fichiers contenu dans le fichier rss

A partir de php 5.4, il faut paramétré pour **htmlentities**, **htmlspecialchars** et **html_entity_decode** l'encodage pour Nuked-Klan

A partir de php 5.6, juste la ligne ci dessus suffit a corrigé aussi les accents.

La 1.8 est une version en cours de développement.

**Comment by luniun** [comment]
Merci a toi . Sa a fonctionner ^^
