### ISSUE TITLE
 Efficiency of captcha

### ISSUE THREAD

**Issue by Zdav** [Nuked-Klan/CMS_Nuked-Klan#97]
New 1.7.14 was setup on web testsite (this site is known for having at least 2-3 spambots at sametime)
http://fragz.fr/index.php

Only 35 minutes later an new spam bot was registered on the website.
Website registration parameters are set by default.
This problem on this version can be resolded if final user active email validation for example.

**Comment by Zdav** [comment]
I have to test this one with new 1.7.15 files.

**Comment by akred** [comment]
Thanks Zdav, do no hesitate to let you know of this efficiency for the next version files.
Yellux will commit them as soon as possible.

**Comment by Zdav** [comment]
Captcha seems to work correctly to block spamBots
